CarRental3/Controllers/ViewCarsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using CarRental3.Models;

namespace CarRental3.Controllers
{
    public class ViewCarsController : Controller
    {
        // GET: ViewCars
       [HttpGet]
        public ActionResult Sedans()
        {
            List<CarModel> SedanList = new List<CarModel>();
            using (DbEntities entity = new DbEntities())
            {
                var result = (from s in entity.Cars
                              where s.Category_Id == 1 & s.CarStatus_Id == 3
                              select s).ToList<Car>();

                foreach (var item in result)
                {
                    SedanList.Add(new CarModel()
                    {
                        ID = item.Car_Id,
                        Registration = item.Registration,
                        Brand = item.brand,
                        Model = item.Model,
                        SeatsNumber = item.SeatNumber,
                        Description = item.Description,
                        CarCategory = item.Car_Category.CarCategory_Name,
                        CarStatus = item.Car_Status.CarStatus_Name,
                        Image = item.Image
                    });
                }
            }
            return View(SedanList);
        }


        [HttpGet]
        public ActionResult FamilyCars()
        {
            List<CarModel> FcarList = new List<CarModel>();
            using (DbEntities entity = new DbEntities())
            {
                var result = (from s in entity.Cars
                              where s.Category_Id == 2 & s.CarStatus_Id == 3
                              select s).ToList<Car>();

                foreach (var item in result)
                {
                    FcarList.Add(new CarModel()
                    {
                        ID = item.Car_Id,
                        Registration = item.Registration,
                        Brand = item.brand,
                        Model = item.Model,
                        SeatsNumber = item.SeatNumber,
                        Description = item.Description,
                        CarCategory = item.Car_Category.CarCategory_Name,
                        CarStatus = item.Car_Status.CarStatus_Name,
                        Image = item.Image
                    });
                }
            }
            return View(FcarList);
        }


        [HttpGet]
        public ActionResult Trucks()
        {
            List<CarModel> TruckList = new List<CarModel>();
            using (DbEntities entity = new DbEntities())
            {
                var result = (from s in entity.Cars
                              where s.Category_Id == 4 & s.CarStatus_Id == 3
                              select s).ToList<Car>();

                foreach (var item in result)
                {
                    TruckList.Add(new CarModel()
                    {
                        ID = item.Car_Id,
                        Registration = item.Registration,
                        Brand = item.brand,
                        Model = item.Model,
                        SeatsNumber = item.SeatNumber,
                        Description = item.Description,
                        CarCategory = item.Car_Category.CarCategory_Name,
                        CarStatus = item.Car_Status.CarStatus_Name,
                        Image = item.Image
                    });
                }
            }
            return View(TruckList);
        }

        public ActionResult RetrieveImage(int id)
        {
            using (DbEntities entity = new DbEntities())
            {
                var Result = (from c in entity.Cars
                              where c.Car_Id == id
                              select c).SingleOrDefault<Car>();

                return File(Result.Image, "image/jpeg");
            }
        }
    }
}

CarRental3/Views/ViewCars/FamilyCars.cshtml
@model IEnumerable<CarRental3.Models.CarModel>

@{
    ViewBag.Title = "Family Cars";
}

<h2>Family Cars</h2>

@*<p>
    @Html.ActionLink("Create New", "Create")
</p>*@
<div class="row">

    @foreach (var item in Model)
    {
        <div class=" col-xs-12 offset-2 col-sm-12 offset-sm-3 col-md-6 offset-md-0 col-lg-4 mb-2 " id="cards">
            <div class="card" style="width: 18rem;">

                <img id="d" class="img-thumbnail" src=@Url.Action("RetrieveImage","ViewCars", new { Id = item.ID}) alt="Car Image" style="height:190px; width:286px;" />

                <div class="card-body">
                    <h5 class="card-title">@item.Brand @item.Model </h5>
                    <h6 class="card-title">@item.SeatsNumber Seater </h6>
                    <p class="card-text">@item.Description</p>
                    <a href="@Url.Action("Create","Booking",new { id = item.ID })" class="btn btn-primary">Book this car</a>
                    @*@Html.ActionLink("Book This Car", "Book", "BookCars", new { id = item.ID, @Class = "btn btn-primary" })*@
                </div>
            </div>
        </div>
    }
</div>

@*<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Registration)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Brand)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Model)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.SeatsNumber)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Description)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.CarCategory)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.CarStatus)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Registration)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Brand)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Model)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.SeatsNumber)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Description)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.CarCategory)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.CarStatus)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { id = item.ID }) |
                @Html.ActionLink("Details", "Details", new { id = item.ID }) |
                @Html.ActionLink("Delete", "Delete", new { id = item.ID })
            </td>
        </tr>
    }

</table>*@

CarRental3/Views/ViewCars/Sedans.cshtml
@model IEnumerable<CarRental3.Models.CarModel>

@{
    ViewBag.Title = "Sedans";
}

<h2>Sedans</h2>

@*<p>
    @Html.ActionLink("Create New", "Create")
</p>*@
<div class="row">

@foreach (var item in Model)
{
     <div class=" col-xs-12 offset-2 col-sm-12 offset-sm-3 col-md-6 offset-md-0 col-lg-4 mb-2 " id="cards">
        <div class="card" style="width: 18rem;">

            <img id="d" class="img-thumbnail" src=@Url.Action("RetrieveImage","ViewCars", new { Id = item.ID}) alt="Car Image" style="height:190px; width:286px;" />

            <div class="card-body">
                <h5 class="card-title">@item.Brand @item.Model </h5>
                <h6 class="card-title">@item.SeatsNumber Seater </h6>
                <p class="card-text">@item.Description</p>
                <a href="@Url.Action("Create","Booking",new { id = item.ID })" class="btn btn-primary">Book this car</a>
                @*@Html.ActionLink("Book This Car", "Book", "BookCars", new { id = item.ID, @Class = "btn btn-primary" })*@
            </div>
        </div>
    </div>
}

   
    @*<div class="col-xs-12 offset-2 col-sm-12 offset-sm-3  col-md-6 offset-md-0  col-lg-4 mb-2 " id="cards">
        <div class="card" style="width: 18rem;">
            <img class="card-img" src="~/Images/Lexus sedan.jpg" alt="Card image cap" style="height:190px" />
            <div class="card-body">
                <h5 class="card-title">Family Car</h5>
                <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
                <a href="#" class="btn btn-primary">More......</a>
            </div>
        </div>
    </div>*@

    @*<div class="col-xs-12 offset-2 col-sm-12 offset-sm-3 col-md-12 offset-md-3 offset-lg-0 col-lg-4 mb-2 " id="cards">
        <div class="card" style="width: 18rem;">

            <img class="card-img" src="~/Images/mini truck.jpg" style="height:190px; width:286px;" />
            <div class="card-body">
                <h5 class="card-title">Trucks</h5>
                <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
                <a href="#" class="btn btn-primary">More......</a>
            </div>
        </div>
    </div>*@
</div>
@*<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Registration)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Brand)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Model)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.SeatsNumber)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Description)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.CarCategory)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.CarStatus)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Registration)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Brand)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Model)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.SeatsNumber)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Description)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.CarCategory)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.CarStatus)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.ID }) |
            @Html.ActionLink("Details", "Details", new { id=item.ID }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.ID })
        </td>
    </tr>
}

</table>*@

CarRental3/Views/ViewCars/Trucks.cshtml
@model IEnumerable<CarRental3.Models.CarModel>

@{
    ViewBag.Title = "Trucks";
}

<h2>Trucks</h2>

@*<p>
    @Html.ActionLink("Create New", "Create")
</p>*@
<div class="row">

    @foreach (var item in Model)
    {
        <div class=" col-xs-12 offset-2 col-sm-12 offset-sm-3 col-md-6 offset-md-0 col-lg-4 mb-2 " id="cards">
            <div class="card" style="width: 18rem;">

                <img id="d" class="img-thumbnail" src=@Url.Action("RetrieveImage","ViewCars", new { Id = item.ID}) alt="Car Image" style="height:190px; width:286px;" />

                <div class="card-body">
                    <h5 class="card-title">@item.Brand @item.Model </h5>
                    <h6 class="card-title">@item.SeatsNumber Seater </h6>
                    <p class="card-text">@item.Description</p>
                    <a href="@Url.Action("Create","Booking",new { id = item.ID })" class="btn btn-primary">Book this car</a>
                    @*@Html.ActionLink("Book This Car", "Book", "BookCars", new { id = item.ID, @Class = "btn btn-primary" })*@
                </div>
            </div>
        </div>
    }
</div>
@*<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Registration)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Brand)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Model)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.SeatsNumber)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Description)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.CarCategory)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.CarStatus)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Registration)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Brand)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Model)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.SeatsNumber)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Description)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.CarCategory)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.CarStatus)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.ID }) |
            @Html.ActionLink("Details", "Details", new { id=item.ID }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.ID })
        </td>
    </tr>
}

</table>*@